/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import BLL.AmenityBLL;
import BLL.AuthBLL;
import BLL.RoomBLL;
import BLL.UserBLL;
import DTOs.AmenityDTO;
import DTOs.Role;
import DTOs.RoomDTO;
import DTOs.RoomSearchCriteriaDTO;
import DTOs.UserDTO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anpha
 */
public class AdminMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMainFrame.class.getName());
    private final RoomBLL roomBLL = new RoomBLL();
    private final UserBLL userBLL = new UserBLL();
    private final AmenityBLL amenityBLL = new AmenityBLL();
    private final AuthBLL authBLL = new AuthBLL();

    /**
     * Creates new form AdminMainFrame
     */
    public AdminMainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        configureFrame();
        wireEvents();
        loadAllData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnApproveRoom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbApproveRoom = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnRoomDetail_tab1 = new javax.swing.JButton();
        btnApproveRoom = new javax.swing.JButton();
        btnDeclineRoom = new javax.swing.JButton();
        pnRoomManage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRoomManage = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnRoomDetail_tab2 = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchRoom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox<>();
        btnSearchRoom = new javax.swing.JButton();
        pnUserManage = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbUserManage = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSearchUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboRole = new javax.swing.JComboBox<>();
        btnSearchUser = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnDeleteUser = new javax.swing.JButton();
        pnAmenityManage = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbAmenityManage = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnAddAmenity = new javax.swing.JButton();
        btnUpdateAmenity = new javax.swing.JButton();
        btnDeleteAmenity = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Hệ thống tìm kiếm phòng trọ");

        btnLogout.setText("Đăng xuất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 985, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(jLabel1))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnApproveRoom.setLayout(new java.awt.BorderLayout());

        tbApproveRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tiêu đề", "Chủ trọ", "Ngày đăng", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbApproveRoom);

        pnApproveRoom.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnRoomDetail_tab1.setText("Xem chi tiết");
        jPanel6.add(btnRoomDetail_tab1);

        btnApproveRoom.setText("Duyệt");
        jPanel6.add(btnApproveRoom);

        btnDeclineRoom.setText("Từ chối");
        jPanel6.add(btnDeclineRoom);

        pnApproveRoom.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Duyệt bài", pnApproveRoom);

        pnRoomManage.setLayout(new java.awt.BorderLayout());

        tbRoomManage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tiêu đề", "Chủ trọ", "Giá thuê", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbRoomManage);

        pnRoomManage.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnRoomDetail_tab2.setText("Xem chi tiết");
        jPanel2.add(btnRoomDetail_tab2);

        btnDeleteRoom.setText("Xóa");
        jPanel2.add(btnDeleteRoom);

        pnRoomManage.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jLabel2.setText("Tìm kiếm");
        jPanel3.add(jLabel2);

        txtSearchRoom.setMinimumSize(new java.awt.Dimension(400, 22));
        txtSearchRoom.setPreferredSize(new java.awt.Dimension(400, 22));
        jPanel3.add(txtSearchRoom);

        jLabel3.setText("Trạng thái");
        jPanel3.add(jLabel3);

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chờ duyệt", "Đã duyệt", "Bị từ chối" }));
        jPanel3.add(cboStatus);

        btnSearchRoom.setText("Tìm/Lọc");
        jPanel3.add(btnSearchRoom);

        pnRoomManage.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab("Quản lý bài đăng", pnRoomManage);

        pnUserManage.setLayout(new java.awt.BorderLayout());

        tbUserManage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Số điện thoại", "Vai trò", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbUserManage);

        pnUserManage.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jLabel4.setText("Tìm kiếm");
        jPanel4.add(jLabel4);

        txtSearchUser.setPreferredSize(new java.awt.Dimension(400, 22));
        jPanel4.add(txtSearchUser);

        jLabel5.setText("Vai trò");
        jPanel4.add(jLabel5);

        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chủ trọ", "Người thuê" }));
        jPanel4.add(cboRole);

        btnSearchUser.setText("Tìm/Lọc");
        jPanel4.add(btnSearchUser);

        pnUserManage.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnDeleteUser.setText("Xóa");
        jPanel5.add(btnDeleteUser);

        pnUserManage.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Quản lý người dùng", pnUserManage);

        pnAmenityManage.setLayout(new java.awt.BorderLayout());

        tbAmenityManage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Tên tiện nghi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbAmenityManage);

        pnAmenityManage.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAddAmenity.setText("Thêm");
        jPanel7.add(btnAddAmenity);

        btnUpdateAmenity.setText("Sửa");
        jPanel7.add(btnUpdateAmenity);

        btnDeleteAmenity.setText("Xóa");
        jPanel7.add(btnDeleteAmenity);

        pnAmenityManage.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Quản lý tiện nghi", pnAmenityManage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configureFrame() {
        cboStatus.setModel(new DefaultComboBoxModel<>(new String[]{"All", "Pending", "Approved"}));
        cboRole.setModel(new DefaultComboBoxModel<>(new String[]{"All", "Landlord", "Tenant", "Admin"}));

        tbApproveRoom.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbRoomManage.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbUserManage.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbAmenityManage.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tbApproveRoom.setModel(tableModel("ID", "Title", "Landlord", "Created", "Status"));
        tbRoomManage.setModel(tableModel("ID", "Title", "Landlord", "Price", "Status", "Available"));
        tbUserManage.setModel(tableModel("ID", "Username", "Name", "Phone", "Role"));
        tbAmenityManage.setModel(tableModel("ID", "Name"));
    }

    private void wireEvents() {
        btnLogout.addActionListener(event -> logout());

        btnRoomDetail_tab1.addActionListener(event -> openSelectedRoom(tbApproveRoom));
        btnRoomDetail_tab2.addActionListener(event -> openSelectedRoom(tbRoomManage));
        btnApproveRoom.addActionListener(event -> approveRoom());
        btnDeclineRoom.addActionListener(event -> declineRoom());
        btnDeleteRoom.addActionListener(event -> deleteRoom());
        btnSearchRoom.addActionListener(event -> loadManagedRooms());
        txtSearchRoom.addActionListener(event -> loadManagedRooms());

        btnSearchUser.addActionListener(event -> loadUsers());
        txtSearchUser.addActionListener(event -> loadUsers());
        btnDeleteUser.addActionListener(event -> deleteUser());

        btnAddAmenity.addActionListener(event -> addAmenity());
        btnUpdateAmenity.addActionListener(event -> updateAmenity());
        btnDeleteAmenity.addActionListener(event -> deleteAmenity());
    }

    private DefaultTableModel tableModel(String... columns) {
        return new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
    }

    private void loadAllData() {
        loadPendingRooms();
        loadManagedRooms();
        loadUsers();
        loadAmenities();
    }

    private void loadPendingRooms() {
        try {
            DefaultTableModel model = (DefaultTableModel) tbApproveRoom.getModel();
            model.setRowCount(0);
            for (RoomDTO room : roomBLL.getPendingRooms()) {
                model.addRow(new Object[]{
                    room.getRoomId(),
                    room.getTitle(),
                    landlordName(room.getLandlordId()),
                    ViewSupport.dateTime(room.getCreatedAt()),
                    ViewSupport.status(room.isStatus())
                });
            }
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void loadManagedRooms() {
        try {
            DefaultTableModel model = (DefaultTableModel) tbRoomManage.getModel();
            model.setRowCount(0);
            for (RoomDTO room : roomBLL.searchRoomsForAdmin(buildRoomCriteria())) {
                model.addRow(new Object[]{
                    room.getRoomId(),
                    room.getTitle(),
                    landlordName(room.getLandlordId()),
                    ViewSupport.money(room.getPrice()),
                    ViewSupport.status(room.isStatus()),
                    ViewSupport.availability(room.isAvailability())
                });
            }
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private RoomSearchCriteriaDTO buildRoomCriteria() {
        RoomSearchCriteriaDTO criteria = new RoomSearchCriteriaDTO();
        criteria.setKeyword(txtSearchRoom.getText());
        int statusIndex = cboStatus.getSelectedIndex();
        if (statusIndex == 1) {
            criteria.setStatus(Boolean.FALSE);
        } else if (statusIndex == 2) {
            criteria.setStatus(Boolean.TRUE);
        }
        criteria.setSortBy(RoomSearchCriteriaDTO.SortBy.CREATED_AT_DESC);
        return criteria;
    }

    private void loadUsers() {
        try {
            DefaultTableModel model = (DefaultTableModel) tbUserManage.getModel();
            model.setRowCount(0);
            for (UserDTO user : userBLL.searchUsers(txtSearchUser.getText(), selectedRoleFilter())) {
                model.addRow(new Object[]{
                    user.getUserId(),
                    user.getUsername(),
                    user.getName(),
                    user.getPhoneNumber(),
                    ViewSupport.role(user.getRole())
                });
            }
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private Role selectedRoleFilter() {
        int index = cboRole.getSelectedIndex();
        if (index == 1) {
            return Role.LANDLORD;
        }
        if (index == 2) {
            return Role.TENANT;
        }
        if (index == 3) {
            return Role.ADMIN;
        }
        return null;
    }

    private void loadAmenities() {
        try {
            DefaultTableModel model = (DefaultTableModel) tbAmenityManage.getModel();
            model.setRowCount(0);
            for (AmenityDTO amenity : amenityBLL.getAllAmenities()) {
                model.addRow(new Object[]{amenity.getAmenityId(), amenity.getName()});
            }
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private String landlordName(int landlordId) throws Exception {
        UserDTO landlord = userBLL.getUserById(landlordId);
        return landlord == null ? String.valueOf(landlordId) : ViewSupport.safe(landlord.getName());
    }

    private void openSelectedRoom(JTable table) {
        try {
            int roomId = selectedId(table);
            new RoomDetailFrame(roomId, this::loadAllData).setVisible(true);
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void approveRoom() {
        try {
            roomBLL.approveRoom(selectedId(tbApproveRoom));
            loadAllData();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void declineRoom() {
        try {
            int roomId = selectedId(tbApproveRoom);
            if (!ViewSupport.confirm(this, "Decline and delete this room?")) {
                return;
            }
            roomBLL.declineRoom(roomId);
            loadAllData();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void deleteRoom() {
        try {
            int roomId = selectedId(tbRoomManage);
            if (!ViewSupport.confirm(this, "Delete this room?")) {
                return;
            }
            roomBLL.deleteRoom(roomId);
            loadAllData();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void deleteUser() {
        try {
            int userId = selectedId(tbUserManage);
            if (!ViewSupport.confirm(this, "Delete this user?")) {
                return;
            }
            userBLL.deleteUser(userId);
            loadUsers();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void addAmenity() {
        String name = JOptionPane.showInputDialog(this, "Amenity name:");
        if (name == null || name.isBlank()) {
            return;
        }

        try {
            amenityBLL.addAmenity(name);
            loadAmenities();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void updateAmenity() {
        try {
            int row = selectedModelRow(tbAmenityManage);
            int amenityId = Integer.parseInt(tbAmenityManage.getModel().getValueAt(row, 0).toString());
            String currentName = String.valueOf(tbAmenityManage.getModel().getValueAt(row, 1));
            String name = JOptionPane.showInputDialog(this, "Amenity name:", currentName);
            if (name == null || name.isBlank()) {
                return;
            }

            amenityBLL.updateAmenity(new AmenityDTO(amenityId, name));
            loadAmenities();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void deleteAmenity() {
        try {
            int amenityId = selectedId(tbAmenityManage);
            if (!ViewSupport.confirm(this, "Delete this amenity?")) {
                return;
            }
            amenityBLL.deleteAmenity(amenityId);
            loadAmenities();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private int selectedId(JTable table) {
        int row = selectedModelRow(table);
        return Integer.parseInt(table.getModel().getValueAt(row, 0).toString());
    }

    private int selectedModelRow(JTable table) {
        int row = table.getSelectedRow();
        if (row < 0) {
            throw new IllegalArgumentException("Please select a row.");
        }
        return table.convertRowIndexToModel(row);
    }

    private void logout() {
        authBLL.logout();
        ViewSupport.openFrame(this, new LoginFrame());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminMainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAmenity;
    private javax.swing.JButton btnApproveRoom;
    private javax.swing.JButton btnDeclineRoom;
    private javax.swing.JButton btnDeleteAmenity;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRoomDetail_tab1;
    private javax.swing.JButton btnRoomDetail_tab2;
    private javax.swing.JButton btnSearchRoom;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JButton btnUpdateAmenity;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnAmenityManage;
    private javax.swing.JPanel pnApproveRoom;
    private javax.swing.JPanel pnRoomManage;
    private javax.swing.JPanel pnUserManage;
    private javax.swing.JTable tbAmenityManage;
    private javax.swing.JTable tbApproveRoom;
    private javax.swing.JTable tbRoomManage;
    private javax.swing.JTable tbUserManage;
    private javax.swing.JTextField txtSearchRoom;
    private javax.swing.JTextField txtSearchUser;
    // End of variables declaration//GEN-END:variables
}
