/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import BLL.AuthBLL;
import BLL.RoomBLL;
import BLL.SessionContext;
import DTOs.Role;
import DTOs.RoomDTO;
import DTOs.RoomDetailDTO;
import DTOs.UserDTO;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author anpha
 */
public class LandlordMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LandlordMainFrame.class.getName());
    private final RoomBLL roomBLL = new RoomBLL();
    private final AuthBLL authBLL = new AuthBLL();

    /**
     * Creates new form LandlordMainFrame
     */
    public LandlordMainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        configureFrame();
        wireEvents();
        loadRooms();
        updateGreeting();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lbGreeting = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnRoomList = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Hệ thống tìm kiếm phòng trọ");

        btnLogout.setText("Đăng xuất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(jLabel1)
                    .addComponent(lbGreeting))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel2.setText("Quản lý phòng trọ");

        javax.swing.GroupLayout pnRoomListLayout = new javax.swing.GroupLayout(pnRoomList);
        pnRoomList.setLayout(pnRoomListLayout);
        pnRoomListLayout.setHorizontalGroup(
            pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1266, Short.MAX_VALUE)
        );
        pnRoomListLayout.setVerticalGroup(
            pnRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnRoomList);

        jButton1.setText("Thêm phòng mới");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configureFrame() {
        pnRoomList.setLayout(new GridLayout(0, 3, 20, 20));
        jButton1.setText("Thêm phòng");
    }

    private void updateGreeting() {
        UserDTO user = SessionContext.getCurrentUser();
        lbGreeting.setText(user != null ? "Xin chào, " + user.getName() + "!" : "");
    }

    private void wireEvents() {
        btnLogout.addActionListener(event -> logout());
        jButton1.addActionListener(event -> openCreateDialog());
    }

    private void loadRooms() {
        try {
            renderRooms(roomBLL.getRoomsForCurrentLandlord());
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void renderRooms(List<RoomDTO> rooms) throws Exception {
        pnRoomList.removeAll();
        if (rooms == null || rooms.isEmpty()) {
            pnRoomList.add(new JLabel("No rooms found."));
        } else {
            for (RoomDTO room : rooms) {
                RoomDetailDTO detail = roomBLL.getRoomDetail(room.getRoomId());
                pnRoomList.add(new RoomCardPanel(detail, Role.LANDLORD,
                        () -> openRoomDetail(room.getRoomId()),
                        () -> openUpdateDialog(detail),
                        () -> deleteRoom(room),
                        () -> toggleAvailability(room)));
            }
        }
        pnRoomList.revalidate();
        pnRoomList.repaint();
    }

    private void openRoomDetail(String roomId) {
        new RoomDetailFrame(roomId, this::loadRooms).setVisible(true);
    }

    private void openCreateDialog() {
        RoomActionDialog dialog = new RoomActionDialog(this, true);
        dialog.setVisible(true);
        if (dialog.isSaved()) {
            loadRooms();
        }
    }

    private void openUpdateDialog(RoomDetailDTO detail) {
        RoomActionDialog dialog = new RoomActionDialog(this, detail);
        dialog.setVisible(true);
        if (dialog.isSaved()) {
            loadRooms();
        }
    }

    private void deleteRoom(RoomDTO room) {
        if (!ViewSupport.confirm(this, "Delete this room?")) {
            return;
        }

        try {
            roomBLL.deleteRoom(room.getRoomId());
            loadRooms();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void toggleAvailability(RoomDTO room) {
        try {
            roomBLL.updateAvailability(room.getRoomId(), !room.isAvailability());
            loadRooms();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void logout() {
        authBLL.logout();
        ViewSupport.openFrame(this, new LoginFrame());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LandlordMainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGreeting;
    private javax.swing.JPanel pnRoomList;
    // End of variables declaration//GEN-END:variables
}
