/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author anpha
 */
public class RoomCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomCardPanel
     */
    public RoomCardPanel() {
        initComponents();
    }

    // ── Public getters cho Controller ──
    public javax.swing.JLabel getLbThumb()           { return lbThumb; }
    public javax.swing.JLabel getLbTitle()           { return lbTitle; }
    public javax.swing.JLabel getLbPrice()           { return lbPrice; }
    public javax.swing.JLabel getLbArea()            { return lbArea; }
    public javax.swing.JLabel getLbAddress()         { return lbAddress; }
    public javax.swing.JLabel getLbAvailability()    { return lbAvailability; }
    public javax.swing.JLabel getLbRating()          { return lbRating; }
    public javax.swing.JLabel getLbStatus()          { return lbStatus; }
    public javax.swing.JPanel getPnAmenity()         { return pnAmenity; }
    public javax.swing.JButton getBtnUpdate()        { return btnUpdate; }
    public javax.swing.JButton getBtnDelete()        { return btnDelete; }
    public javax.swing.JButton getBtnAvailability()  { return btnAvailability; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbThumb = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbArea = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnAmenity = new javax.swing.JPanel();
        lbAvailability = new javax.swing.JLabel();
        lbRating = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAvailability = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(380, 420));

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitle.setText("<Tiêu đề>");

        lbPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPrice.setForeground(new java.awt.Color(255, 0, 51));
        lbPrice.setText("<Giá tiền>");

        lbArea.setForeground(new java.awt.Color(153, 153, 153));
        lbArea.setText("<Diện tích>");

        lbAddress.setText("<Địa chỉ>");

        jLabel4.setText("Tiện nghi");

        pnAmenity.setMinimumSize(new java.awt.Dimension(30, 30));
        pnAmenity.setLayout(new java.awt.GridLayout(1, 3, 15, 10));

        lbAvailability.setText("<Còn/hết>");

        lbRating.setText("<Đánh giá (số sao)>");

        lbStatus.setText("<Chờ/đã duyệt>");

        btnUpdate.setText("Sửa");

        btnDelete.setText("Xóa");

        btnAvailability.setText("Đổi còn/hết");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbThumb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAvailability))
                    .addComponent(pnAmenity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lbAddress))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPrice)
                        .addGap(18, 18, 18)
                        .addComponent(lbArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(lbRating))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAvailability)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbStatus)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbThumb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAvailability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnAmenity, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrice)
                    .addComponent(lbArea)
                    .addComponent(lbRating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatus)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnAvailability))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailability;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbAvailability;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbRating;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbThumb;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnAmenity;
    // End of variables declaration//GEN-END:variables
}
