/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import BLL.ReviewBLL;
import BLL.RoomBLL;
import BLL.SessionContext;
import DTOs.AmenityDTO;
import DTOs.Role;
import DTOs.RoomDTO;
import DTOs.RoomDetailDTO;
import DTOs.RoomImageDTO;
import DTOs.UserDTO;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author anpha
 */
public class RoomDetailFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoomDetailFrame.class.getName());
    private final RoomBLL roomBLL = new RoomBLL();
    private final ReviewBLL reviewBLL = new ReviewBLL();
    private RoomDetailDTO currentDetail;
    private Runnable onChanged;

    /**
     * Creates new form RoomDetailFrame
     */
    public RoomDetailFrame() {
        initComponents();
        configureFrame();
        wireEvents();
    }

    public RoomDetailFrame(int roomId, Runnable onChanged) {
        this();
        this.onChanged = onChanged;
        loadDetail(roomId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMainImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnImageList = new javax.swing.JPanel();
        lbAvailability = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbArea = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnAmenity = new javax.swing.JPanel();
        lbRating = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbDescription = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnReviewList = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtReview = new javax.swing.JTextField();
        cboRating = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        lbMainImage.setText("jLabel1");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(pnImageList);

        lbAvailability.setText("<Còn/hết>");

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitle.setText("<Tiêu đề>");

        lbPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPrice.setForeground(new java.awt.Color(255, 0, 51));
        lbPrice.setText("<Giá tiền>");

        lbArea.setForeground(new java.awt.Color(153, 153, 153));
        lbArea.setText("<Diện tích>");

        lbAddress.setText("<Địa chỉ>");

        jLabel4.setText("Tiện nghi");

        pnAmenity.setBackground(java.awt.SystemColor.controlHighlight);
        pnAmenity.setMinimumSize(new java.awt.Dimension(30, 30));
        pnAmenity.setLayout(new java.awt.GridLayout(1, 0, 15, 10));

        lbRating.setText("<Rating>");

        jLabel1.setText("Mô tả");

        lbDescription.setText("<Mô tả>");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Liên hệ");

        lbPhone.setText("<Số điện thoại chủ trọ>");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout pnReviewListLayout = new javax.swing.GroupLayout(pnReviewList);
        pnReviewList.setLayout(pnReviewListLayout);
        pnReviewListLayout.setHorizontalGroup(
            pnReviewListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        pnReviewListLayout.setVerticalGroup(
            pnReviewListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(pnReviewList);

        jLabel3.setText("Đánh giá");

        txtReview.setText("<Nhập đánh giá>");

        cboRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "4", "3", "2", "1" }));

        btnSubmit.setText("Đăng");

        jLabel5.setText("sao");

        btnUpdate.setText("Sửa bài");

        btnDelete.setText("Xóa bài");

        lbStatus.setText("<Chờ duyệt/đã duyệt>");

        jButton1.setText("Đổi còn/hết");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMainImage, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbRating)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbAddress)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtReview, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboRating, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(12, 12, 12)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnAmenity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbArea)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMainImage, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAvailability))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbRating)
                            .addComponent(lbStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnAmenity, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAddress)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrice)
                            .addComponent(lbArea))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbPhone)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReview, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboRating, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configureFrame() {
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pnImageList.setLayout(new FlowLayout(FlowLayout.LEFT, 8, 8));
        pnReviewList.setLayout(new BoxLayout(pnReviewList, BoxLayout.Y_AXIS));
        txtReview.setText("");
        btnUpdate.setText("Edit room");
        btnDelete.setText("Delete room");
        jButton1.setText("Toggle availability");
    }

    private void wireEvents() {
        btnSubmit.addActionListener(event -> submitReview());
        btnUpdate.addActionListener(event -> openUpdateDialog());
        btnDelete.addActionListener(event -> deleteRoom());
        jButton1.addActionListener(event -> toggleAvailability());
    }

    private void loadDetail(int roomId) {
        try {
            currentDetail = roomBLL.getRoomDetail(roomId);
            if (currentDetail == null) {
                ViewSupport.showInfo(this, "Room not found.");
                dispose();
                return;
            }
            bindDetail();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
            dispose();
        }
    }

    private void bindDetail() {
        RoomDTO room = currentDetail.getRoom();
        lbTitle.setText(ViewSupport.html(room.getTitle()));
        lbAvailability.setText(ViewSupport.availability(room.isAvailability()));
        lbRating.setText(ViewSupport.rating(room.getAverageRating(), room.getReviewCount()));
        lbStatus.setText(ViewSupport.status(room.isStatus()));
        lbDescription.setText(ViewSupport.html(room.getDescription()));
        lbAddress.setText(ViewSupport.html(room.getAddress()));
        lbPrice.setText(ViewSupport.money(room.getPrice()));
        lbArea.setText(ViewSupport.area(room.getArea()));
        bindLandlord(currentDetail.getLandlord());
        renderAmenities(currentDetail.getAmenities());
        renderImages(currentDetail.getImages());
        renderReviews();
        configureByRole();
    }

    private void bindLandlord(UserDTO landlord) {
        if (landlord == null) {
            lbPhone.setText("-");
            return;
        }
        lbPhone.setText(ViewSupport.safe(landlord.getName()) + " - " + ViewSupport.safe(landlord.getPhoneNumber()));
    }

    private void renderAmenities(List<AmenityDTO> amenities) {
        pnAmenity.removeAll();
        if (amenities == null || amenities.isEmpty()) {
            pnAmenity.add(new JLabel("-"));
        } else {
            for (AmenityDTO amenity : amenities) {
                pnAmenity.add(new JLabel(ViewSupport.safe(amenity.getName())));
            }
        }
        pnAmenity.revalidate();
        pnAmenity.repaint();
    }

    private void renderImages(List<RoomImageDTO> images) {
        pnImageList.removeAll();
        if (images == null || images.isEmpty()) {
            ViewSupport.setScaledImage(lbMainImage, null, 550, 560);
        } else {
            ViewSupport.setScaledImage(lbMainImage, images.get(0).getImagePath(), 550, 560);
            for (RoomImageDTO image : images) {
                JLabel thumb = new JLabel();
                thumb.setPreferredSize(new Dimension(90, 70));
                thumb.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                ViewSupport.setScaledImage(thumb, image.getImagePath(), 90, 70);
                thumb.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent event) {
                        ViewSupport.setScaledImage(lbMainImage, image.getImagePath(), 550, 560);
                    }
                });
                pnImageList.add(thumb);
            }
        }
        pnImageList.revalidate();
        pnImageList.repaint();
    }

    private void renderReviews() {
        pnReviewList.removeAll();
        if (currentDetail.getReviews() == null || currentDetail.getReviews().isEmpty()) {
            pnReviewList.add(new JLabel("No reviews."));
        } else {
            for (DTOs.ReviewDTO review : currentDetail.getReviews()) {
                pnReviewList.add(new ReviewPanel(review));
            }
        }
        pnReviewList.revalidate();
        pnReviewList.repaint();
    }

    private void configureByRole() {
        Role role = SessionContext.getCurrentRole();
        boolean tenant = role == Role.TENANT;
        boolean landlord = role == Role.LANDLORD;
        boolean admin = role == Role.ADMIN;

        txtReview.setVisible(tenant);
        cboRating.setVisible(tenant);
        btnSubmit.setVisible(tenant);
        jLabel5.setVisible(tenant);

        btnUpdate.setVisible(landlord);
        jButton1.setVisible(landlord);
        btnDelete.setVisible(landlord || admin);
    }

    private void submitReview() {
        try {
            int rating = Integer.parseInt(String.valueOf(cboRating.getSelectedItem()));
            reviewBLL.addReview(currentDetail.getRoom().getRoomId(), rating, txtReview.getText());
            txtReview.setText("");
            notifyChanged();
            loadDetail(currentDetail.getRoom().getRoomId());
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void openUpdateDialog() {
        RoomActionDialog dialog = new RoomActionDialog(this, currentDetail);
        dialog.setVisible(true);
        if (dialog.isSaved()) {
            notifyChanged();
            loadDetail(currentDetail.getRoom().getRoomId());
        }
    }

    private void deleteRoom() {
        if (!ViewSupport.confirm(this, "Delete this room?")) {
            return;
        }

        try {
            roomBLL.deleteRoom(currentDetail.getRoom().getRoomId());
            notifyChanged();
            dispose();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void toggleAvailability() {
        try {
            RoomDTO room = currentDetail.getRoom();
            roomBLL.updateAvailability(room.getRoomId(), !room.isAvailability());
            notifyChanged();
            loadDetail(room.getRoomId());
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void notifyChanged() {
        if (onChanged != null) {
            onChanged.run();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RoomDetailFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboRating;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbAvailability;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbMainImage;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbRating;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnAmenity;
    private javax.swing.JPanel pnImageList;
    private javax.swing.JPanel pnReviewList;
    private javax.swing.JTextField txtReview;
    // End of variables declaration//GEN-END:variables
}
