/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DTOs.AmenityDTO;
import DTOs.Role;
import DTOs.RoomDTO;
import DTOs.RoomDetailDTO;
import DTOs.RoomImageDTO;
import java.awt.Component;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author anpha
 */
public class RoomCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomCardPanel
     */
    public RoomCardPanel() {
        initComponents();
    }

    public RoomCardPanel(RoomDetailDTO detail, Role role, Runnable onOpenDetail,
            Runnable onUpdate, Runnable onDelete, Runnable onToggleAvailability) {
        this();
        bindData(detail);
        wireEvents(role, onOpenDetail, onUpdate, onDelete, onToggleAvailability);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbThumb = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbArea = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnAmenity = new javax.swing.JPanel();
        lbAvailability = new javax.swing.JLabel();
        lbRating = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(380, 420));

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitle.setText("<Tiêu đề>");

        lbPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPrice.setForeground(new java.awt.Color(255, 0, 51));
        lbPrice.setText("<Giá tiền>");

        lbArea.setForeground(new java.awt.Color(153, 153, 153));
        lbArea.setText("<Diện tích>");

        lbAddress.setText("<Địa chỉ>");

        jLabel4.setText("Tiện nghi");

        pnAmenity.setMinimumSize(new java.awt.Dimension(30, 30));
        pnAmenity.setLayout(new java.awt.GridLayout(1, 3, 15, 10));

        lbAvailability.setText("<Còn/hết>");

        lbRating.setText("<Đánh giá (số sao)>");

        lbStatus.setText("<Chờ/đã duyệt>");

        btnUpdate.setText("Sửa");

        btnDelete.setText("Xóa");

        jButton1.setText("Đổi còn/hết");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbThumb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAvailability))
                    .addComponent(pnAmenity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lbAddress))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPrice)
                        .addGap(18, 18, 18)
                        .addComponent(lbArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(lbRating))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbStatus)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbThumb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAvailability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnAmenity, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrice)
                    .addComponent(lbArea)
                    .addComponent(lbRating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatus)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(jButton1))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bindData(RoomDetailDTO detail) {
        if (detail == null || detail.getRoom() == null) {
            return;
        }

        RoomDTO room = detail.getRoom();
        lbTitle.setText(ViewSupport.html(room.getTitle()));
        lbPrice.setText(ViewSupport.money(room.getPrice()));
        lbArea.setText(ViewSupport.area(room.getArea()));
        lbAddress.setText(ViewSupport.html(room.getAddress()));
        lbAvailability.setText(ViewSupport.availability(room.isAvailability()));
        lbRating.setText(ViewSupport.rating(room.getAverageRating(), room.getReviewCount()));
        lbStatus.setText(ViewSupport.status(room.isStatus()));
        renderAmenities(detail.getAmenities());
        renderThumbnail(detail.getImages());
        setBorder(BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
    }

    private void renderAmenities(List<AmenityDTO> amenities) {
        pnAmenity.removeAll();
        if (amenities == null || amenities.isEmpty()) {
            pnAmenity.add(new JLabel("-"));
        } else {
            int count = Math.min(amenities.size(), 3);
            for (int i = 0; i < count; i++) {
                pnAmenity.add(new JLabel(ViewSupport.safe(amenities.get(i).getName())));
            }
        }
        pnAmenity.revalidate();
        pnAmenity.repaint();
    }

    private void renderThumbnail(List<RoomImageDTO> images) {
        String imagePath = null;
        if (images != null && !images.isEmpty()) {
            imagePath = images.get(0).getImagePath();
        }
        ViewSupport.setScaledImage(lbThumb, imagePath, 380, 200);
    }

    private void wireEvents(Role role, Runnable onOpenDetail,
            Runnable onUpdate, Runnable onDelete, Runnable onToggleAvailability) {
        MouseAdapter openDetailMouseListener = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent event) {
                if (event.getClickCount() >= 2 && onOpenDetail != null) {
                    onOpenDetail.run();
                }
            }
        };
        registerOpenDetailListener(this, openDetailMouseListener);

        btnUpdate.setVisible(onUpdate != null);
        btnDelete.setVisible(onDelete != null);
        jButton1.setVisible(onOpenDetail != null || onToggleAvailability != null);

        if (onUpdate != null) {
            btnUpdate.addActionListener(event -> onUpdate.run());
        }
        if (onDelete != null) {
            btnDelete.addActionListener(event -> onDelete.run());
        }

        if (role == Role.TENANT && onOpenDetail != null) {
            jButton1.setText("Detail");
            jButton1.addActionListener(event -> onOpenDetail.run());
        } else if (onToggleAvailability != null) {
            jButton1.setText("Toggle");
            jButton1.addActionListener(event -> onToggleAvailability.run());
        } else {
            jButton1.setVisible(false);
        }
    }

    private void registerOpenDetailListener(Component component, MouseAdapter listener) {
        if (component instanceof JButton) {
            return;
        }

        component.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        component.addMouseListener(listener);
        if (component instanceof Container) {
            for (Component child : ((Container) component).getComponents()) {
                registerOpenDetailListener(child, listener);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbAvailability;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbRating;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbThumb;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnAmenity;
    // End of variables declaration//GEN-END:variables
}
