/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import BLL.AmenityBLL;
import BLL.RoomBLL;
import DTOs.AmenityDTO;
import DTOs.RoomDTO;
import DTOs.RoomDetailDTO;
import DTOs.RoomImageDTO;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author anpha
 */
public class RoomActionDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoomActionDialog.class.getName());
    private final RoomBLL roomBLL = new RoomBLL();
    private final AmenityBLL amenityBLL = new AmenityBLL();
    private final Map<JCheckBox, AmenityDTO> amenityByCheckBox = new LinkedHashMap<>();
    private final List<AmenityDTO> allAmenities = new ArrayList<>();
    private final List<String> imagePaths = new ArrayList<>();
    private RoomDetailDTO currentDetail;
    private boolean saved;

    /**
     * Creates new form RoomActionDialog
     */
    public RoomActionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configureDialog(parent);
        wireEvents();
        loadAmenities();
    }

    public RoomActionDialog(java.awt.Frame parent, RoomDetailDTO detail) {
        this(parent, true);
        currentDetail = detail;
        populateDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnAmenity = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        pnImageList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thêm phòng mới");

        jLabel2.setText("Tiêu đề");

        jLabel3.setText("Mô tả");

        jLabel4.setText("Tiện nghi");

        pnAmenity.setLayout(new java.awt.GridLayout(0, 3, 20, 20));

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Giá tiền");

        jLabel7.setText("Diện tích");

        btnBrowse.setText("Chọn ảnh");

        btnExit.setText("Hủy");

        btnSave.setText("Lưu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(253, 253, 253)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTitle)
                                        .addComponent(txtDescription)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(108, 108, 108)
                                    .addComponent(btnExit)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave)
                                    .addGap(127, 127, 127))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnAmenity, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPrice)
                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtArea))
                                .addComponent(pnImageList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnBrowse)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnAmenity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnImageList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBrowse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnSave))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isSaved() {
        return saved;
    }

    private void configureDialog(java.awt.Frame parent) {
        setLocationRelativeTo(parent);
        setResizable(false);
        pnImageList.setLayout(new FlowLayout(FlowLayout.LEFT, 8, 8));
        jLabel1.setText("Add room");
    }

    private void wireEvents() {
        btnExit.addActionListener(event -> dispose());
        btnSave.addActionListener(event -> saveRoom());
        btnBrowse.addActionListener(event -> browseImages());
    }

    private void loadAmenities() {
        try {
            allAmenities.clear();
            allAmenities.addAll(amenityBLL.getAllAmenities());
            renderAmenities();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void populateDetail() {
        if (currentDetail == null || currentDetail.getRoom() == null) {
            return;
        }

        RoomDTO room = currentDetail.getRoom();
        jLabel1.setText("Edit room");
        txtTitle.setText(ViewSupport.safe(room.getTitle()));
        txtDescription.setText(ViewSupport.safe(room.getDescription()));
        txtAddress.setText(ViewSupport.safe(room.getAddress()));
        txtPrice.setText(String.valueOf(room.getPrice()));
        txtArea.setText(String.valueOf(room.getArea()));

        imagePaths.clear();
        for (RoomImageDTO image : currentDetail.getImages()) {
            if (image.getImagePath() != null && !image.getImagePath().isBlank()) {
                imagePaths.add(image.getImagePath());
            }
        }

        renderAmenities();
        renderImages();
    }

    private void renderAmenities() {
        pnAmenity.removeAll();
        amenityByCheckBox.clear();

        Set<Integer> selectedAmenityIds = selectedAmenityIdsFromDetail();
        if (allAmenities.isEmpty()) {
            pnAmenity.add(new JLabel("No amenities."));
        } else {
            for (AmenityDTO amenity : allAmenities) {
                JCheckBox checkBox = new JCheckBox(ViewSupport.safe(amenity.getName()));
                checkBox.setSelected(selectedAmenityIds.contains(amenity.getAmenityId()));
                amenityByCheckBox.put(checkBox, amenity);
                pnAmenity.add(checkBox);
            }
        }

        pnAmenity.revalidate();
        pnAmenity.repaint();
    }

    private Set<Integer> selectedAmenityIdsFromDetail() {
        Set<Integer> ids = new HashSet<>();
        if (currentDetail == null || currentDetail.getAmenities() == null) {
            return ids;
        }

        for (AmenityDTO amenity : currentDetail.getAmenities()) {
            ids.add(amenity.getAmenityId());
        }
        return ids;
    }

    private void browseImages() {
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "jpeg", "png", "gif", "bmp"));
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        for (File file : chooser.getSelectedFiles()) {
            String path = file.getAbsolutePath();
            if (!imagePaths.contains(path)) {
                imagePaths.add(path);
            }
        }
        renderImages();
    }

    private void renderImages() {
        pnImageList.removeAll();
        if (imagePaths.isEmpty()) {
            pnImageList.add(new JLabel("No images selected."));
        } else {
            for (String path : new ArrayList<>(imagePaths)) {
                JLabel thumb = new JLabel();
                thumb.setPreferredSize(new Dimension(90, 70));
                thumb.setToolTipText("Double click to remove");
                thumb.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                ViewSupport.setScaledImage(thumb, path, 90, 70);
                thumb.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent event) {
                        if (event.getClickCount() >= 2) {
                            imagePaths.remove(path);
                            renderImages();
                        }
                    }
                });
                pnImageList.add(thumb);
            }
        }
        pnImageList.revalidate();
        pnImageList.repaint();
    }

    private void saveRoom() {
        try {
            RoomDetailDTO detail = buildRoomDetail();
            if (currentDetail == null) {
                roomBLL.createRoom(detail);
            } else {
                roomBLL.updateRoom(detail);
            }
            saved = true;
            ViewSupport.showInfo(this, "Room saved.");
            dispose();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private RoomDetailDTO buildRoomDetail() {
        RoomDTO room = currentDetail == null ? new RoomDTO() : currentDetail.getRoom();
        room.setTitle(txtTitle.getText().trim());
        room.setDescription(txtDescription.getText().trim());
        room.setAddress(txtAddress.getText().trim());
        room.setPrice(parseDouble(txtPrice, "Price"));
        room.setArea(parseDouble(txtArea, "Area"));

        RoomDetailDTO detail = new RoomDetailDTO();
        detail.setRoom(room);
        detail.setAmenities(selectedAmenities());
        detail.setImages(selectedImages(room.getRoomId()));
        return detail;
    }

    private List<AmenityDTO> selectedAmenities() {
        List<AmenityDTO> amenities = new ArrayList<>();
        for (Map.Entry<JCheckBox, AmenityDTO> entry : amenityByCheckBox.entrySet()) {
            if (entry.getKey().isSelected()) {
                amenities.add(entry.getValue());
            }
        }
        return amenities;
    }

    private List<RoomImageDTO> selectedImages(int roomId) {
        List<RoomImageDTO> images = new ArrayList<>();
        for (String imagePath : imagePaths) {
            images.add(new RoomImageDTO(0, roomId, imagePath));
        }
        return images;
    }

    private double parseDouble(JTextField field, String fieldName) {
        try {
            return Double.parseDouble(field.getText().trim());
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException(fieldName + " must be a number");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RoomActionDialog dialog = new RoomActionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnAmenity;
    private javax.swing.JPanel pnImageList;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
