/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import BLL.AmenityBLL;
import BLL.AuthBLL;
import BLL.RoomBLL;
import DTOs.AmenityDTO;
import DTOs.Role;
import DTOs.RoomDTO;
import DTOs.RoomDetailDTO;
import DTOs.RoomSearchCriteriaDTO;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author anpha
 */
public class TenantMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TenantMainFrame.class.getName());
    private final RoomBLL roomBLL = new RoomBLL();
    private final AmenityBLL amenityBLL = new AmenityBLL();
    private final AuthBLL authBLL = new AuthBLL();
    private final Map<JCheckBox, AmenityDTO> amenityByCheckBox = new LinkedHashMap<>();

    /**
     * Creates new form TenantMainFrame
     */
    public TenantMainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        wireEvents();
        loadAmenities();
        loadRooms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSort = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        pnSort = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rdoPrice = new javax.swing.JRadioButton();
        rdoReview = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtMinPrice = new javax.swing.JTextField();
        txtMaxPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnApply = new javax.swing.JButton();
        pnAmenity = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnRoomList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Hệ thống tìm kiếm phòng trọ");

        btnLogout.setText("Đăng xuất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(jLabel1))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnSort.setBackground(new java.awt.Color(255, 255, 255));
        pnSort.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Sắp xếp theo");

        btgSort.add(rdoPrice);
        rdoPrice.setText("Giá tiền");

        btgSort.add(rdoReview);
        rdoReview.setText("Đánh giá");

        jLabel3.setText("Khoảng giá");

        jLabel4.setText("Tiện nghi");

        btnApply.setText("Áp dụng");

        pnAmenity.setBackground(new java.awt.Color(255, 255, 255));
        pnAmenity.setLayout(new java.awt.GridLayout(0, 3, 15, 10));

        javax.swing.GroupLayout pnSortLayout = new javax.swing.GroupLayout(pnSort);
        pnSort.setLayout(pnSortLayout);
        pnSortLayout.setHorizontalGroup(
            pnSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSortLayout.createSequentialGroup()
                .addGroup(pnSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSortLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(pnSortLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(rdoPrice)
                        .addGap(18, 18, 18)
                        .addComponent(rdoReview)))
                .addGroup(pnSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSortLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(pnSortLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(txtMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(pnSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSortLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(pnSortLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnAmenity, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnSortLayout.setVerticalGroup(
            pnSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSortLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSortLayout.createSequentialGroup()
                        .addGroup(pnSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoPrice)
                            .addComponent(rdoReview)
                            .addComponent(txtMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(btnApply)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addComponent(pnAmenity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnSearch.setText("Tìm kiếm");

        pnRoomList.setLayout(new java.awt.GridLayout(0, 3, 20, 20));
        jScrollPane1.setViewportView(pnRoomList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wireEvents() {
        btnLogout.addActionListener(event -> logout());
        btnSearch.addActionListener(event -> searchRooms());
        btnApply.addActionListener(event -> searchRooms());
        txtSearch.addActionListener(event -> searchRooms());
    }

    private void loadAmenities() {
        try {
            pnAmenity.removeAll();
            amenityByCheckBox.clear();
            for (AmenityDTO amenity : amenityBLL.getAllAmenities()) {
                JCheckBox checkBox = new JCheckBox(ViewSupport.safe(amenity.getName()));
                amenityByCheckBox.put(checkBox, amenity);
                pnAmenity.add(checkBox);
            }
            pnAmenity.revalidate();
            pnAmenity.repaint();
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void loadRooms() {
        try {
            renderRooms(roomBLL.getAvailableRooms());
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private void searchRooms() {
        try {
            renderRooms(roomBLL.searchAvailableRooms(buildCriteria()));
        } catch (Exception ex) {
            ViewSupport.showError(this, ex);
        }
    }

    private RoomSearchCriteriaDTO buildCriteria() {
        RoomSearchCriteriaDTO criteria = new RoomSearchCriteriaDTO();
        criteria.setKeyword(txtSearch.getText());
        criteria.setMinPrice(parseOptionalDouble(txtMinPrice.getText(), "Minimum price"));
        criteria.setMaxPrice(parseOptionalDouble(txtMaxPrice.getText(), "Maximum price"));
        criteria.setAmenityIds(selectedAmenityIds());

        if (rdoPrice.isSelected()) {
            criteria.setSortBy(RoomSearchCriteriaDTO.SortBy.PRICE_ASC);
        } else if (rdoReview.isSelected()) {
            criteria.setSortBy(RoomSearchCriteriaDTO.SortBy.RATING_DESC);
        } else {
            criteria.setSortBy(RoomSearchCriteriaDTO.SortBy.CREATED_AT_DESC);
        }
        return criteria;
    }

    private Double parseOptionalDouble(String value, String fieldName) {
        if (value == null || value.isBlank()) {
            return null;
        }

        try {
            return Double.valueOf(value.trim());
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException(fieldName + " must be a number");
        }
    }

    private List<Integer> selectedAmenityIds() {
        List<Integer> ids = new ArrayList<>();
        for (Map.Entry<JCheckBox, AmenityDTO> entry : amenityByCheckBox.entrySet()) {
            if (entry.getKey().isSelected()) {
                ids.add(entry.getValue().getAmenityId());
            }
        }
        return ids;
    }

    private void renderRooms(List<RoomDTO> rooms) throws Exception {
        pnRoomList.removeAll();
        if (rooms == null || rooms.isEmpty()) {
            pnRoomList.add(new JLabel("No rooms found."));
        } else {
            for (RoomDTO room : rooms) {
                RoomDetailDTO detail = roomBLL.getRoomDetail(room.getRoomId());
                pnRoomList.add(new RoomCardPanel(detail, Role.TENANT,
                        () -> openRoomDetail(room.getRoomId()), null, null, null));
            }
        }
        pnRoomList.revalidate();
        pnRoomList.repaint();
    }

    private void openRoomDetail(int roomId) {
        new RoomDetailFrame(roomId, this::searchRooms).setVisible(true);
    }

    private void logout() {
        authBLL.logout();
        ViewSupport.openFrame(this, new LoginFrame());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TenantMainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSort;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnAmenity;
    private javax.swing.JPanel pnRoomList;
    private javax.swing.JPanel pnSort;
    private javax.swing.JRadioButton rdoPrice;
    private javax.swing.JRadioButton rdoReview;
    private javax.swing.JTextField txtMaxPrice;
    private javax.swing.JTextField txtMinPrice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
